### ISSUE TITLE
Not Able To Call Functions

### ISSUE THREAD

**Issue by technotip** [junaidpv/youtube#1]
I've included the class file and created an Object and trying to call function, but am not getting any return values:

```
<?php

require_once("youtube.php");

$url = "https://www.youtube.com/watch?v=Q4hortBQmTc";

$data = new Youtube($url);

print_r($data->get_video_data_by_quality());

?>
```

youtube.php file is in the same directory as above file.

**Comment by junaidpv** [comment]
I wrote it several years back while working for a project involved taking video from YouTube.

I just tried the test script and see it no longer working. I see youtube changed its page structure so the script is unable to get necessary information.

I suggest you to have look on https://github.com/ytdl-org/youtube-dl . it is command line program which you may call from your php script. That is a well maintained project and widely used. Me too use it regularly.

**Comment by technotip** [comment]
Ok, thank you ..
